import type { Metadata } from "next";
import "./globals.css";
import { asgardFont, poppins } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${asgardFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
